// 测试脚本：验证变量是否正确添加到小眼睛
console.log('=== 投资项目方案报告生成模块变量检查 ===')
console.log('检查的变量：')
console.log('1. {{land_transfer}} - 土地流转信息')
console.log('2. {{project_overview}} - 项目概况')  
console.log('3. {{operation_load}} - 运营负荷')
console.log('')
console.log('=== 检查方法 ===')
console.log('1. 在报告生成页面，点击提示词变量按钮（小眼睛图标）')
console.log('2. 查看是否有以下变量出现在列表中：')
console.log('3. 如果变量为空，检查对应的数据源是否为空')
console.log('4. 刷新页面后重试')
console.log('')
console.log('=== 预期结果 ===')
console.log('修复后，所有变量都应该：')
console.log('- 在小眼睛中可见')
console.log('- 与LLM调用使用的数据一致')
console.log('- 变量值不为空时显示实际JSON数据')
console.log('- 变量值为空时显示"null"或"[]"')